version: "3.9"

services:
  db:
    image: postgres:15.3-alpine
    container_name: app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: "loco"
      POSTGRES_DB: needs_development
    ports:
      - "5432:5432"
    volumes:
      # persistent data
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-appdb}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  needs:
    # Builds from your custom Dockerfile in ./backend
    build:
      context: .
      dockerfile: dockerfile
    container_name: needs
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5150:5150"

volumes:
  db_data:
