//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::feelings::Entity as Feelings;
pub use super::invites::Entity as Invites;
pub use super::needs::Entity as Needs;
pub use super::users::Entity as Users;
